name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:      # Allow manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: hanumanthuNani
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Generate Snake"
          add: "dist/github-contribution-grid-snake.svg"
